language: python
sudo: false
cache: pip
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-dj17
    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 2.7
      env: TOXENV=py27-dj19
    - python: 2.7
      env: TOXENV=py27-dj110
    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.5
      env: TOXENV=py35-dj18
    - python: 3.5
      env: TOXENV=py35-dj19
    - python: 3.5
      env: TOXENV=py35-dj110
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.5
      env: TOXENV=py35-djdev
    - python: 3.6
      env: TOXENV=py36-dj18
    - python: 3.6
      env: TOXENV=py36-dj19
    - python: 3.6
      env: TOXENV=py36-dj110
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.6
      env: TOXENV=py36-djdev
  allow_failures:
    - env: TOXENV=py35-djdev
    - env: TOXENV=py36-djdev
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
