# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('tooth_diagram', models.CharField(max_length=50)),
                ('tooth_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restoration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='restoration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycrm.Restoration'),
        ),
    ]
