# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
