# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0003_auto_20170727_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateField(),
        ),
    ]
