# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0004_auto_20170727_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
    ]
