# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0005_auto_20170727_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
