# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0006_auto_20170727_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Địa Chỉ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(verbose_name='Thành Tiền'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateField(verbose_name='Ngày Tạo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='MSKH'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ghi Chú'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='restoration_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycrm.Restoration', verbose_name='Yêu Cầu Phục Hình'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tooth_diagram',
            field=models.CharField(max_length=50, verbose_name='Sơ đồ răng'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tooth_number',
            field=models.IntegerField(verbose_name='Số Lượng Răng'),
        ),
        migrations.AlterField(
            model_name='restoration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='MS'),
        ),
        migrations.AlterField(
            model_name='restoration',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='restoration',
            name='price',
            field=models.IntegerField(verbose_name='Giá Tiền'),
        ),
    ]
